CREATE SCHEMA IF NOT EXISTS PP;
SET SCHEMA PP;
CREATE TABLE IF NOT EXISTS PP.TB_CHAV_CONE_NOVO_MOBL(
	CD_CONE_MOBL_PESS_JURI VARCHAR(255) PRIMARY KEY,
	CD_CNFD_CHAV_CONE VARCHAR(255),
	CD_SESS_PESS_JURI VARCHAR(255),
	CD_DINA_CRIP_CONE VARCHAR(255),
	CD_CHAV_PUBL_DISV_CLIE VARCHAR(255)
);